import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../../app/store";

export interface PlayState {
  isPlaying: boolean;
  isStopped: boolean;
  isLooped: boolean;
}

const initialState: PlayState = {
  isPlaying: false,
  isStopped: false,
  isLooped: true,
};

export const playControllersSlice = createSlice({
  name: "playStatus",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    play: (state) => {
      state.isPlaying = true;
      state.isStopped = false;
    },
    pause: (state) => {
      state.isPlaying = false;
    },
    stop: (state) => {
      state.isStopped = true;
      state.isPlaying = false;
    },
    loop: (state) => {
      state.isLooped = state.isLooped ? false : true;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const { play, pause, stop, loop } = playControllersSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectIsPlaying = (state: RootState) => state.playStatus.isPlaying;
export const selectIsStopped = (state: RootState) => state.playStatus.isStopped;
export const selectIsLooped = (state: RootState) => state.playStatus.isLooped;
export default playControllersSlice.reducer;
